### ISSUE TITLE
Support more character classes (meta-issue)

### ISSUE THREAD

**Issue by kddnewton** [kddnewton/regular_expression#6]
At the moment we only support very basic character classes. We should support all of the character classes that Ruby supports, which includes:

* [x] `/\w/` - A word character `([a-zA-Z0-9_])`
* [x] `/\W/` - A non-word character `([^a-zA-Z0-9_])`
* [x] `/\d/` - A digit character `([0-9])`
* [x] `/\D/` - A non-digit character `([^0-9])`
* [x] #24
* [x] #40
* [x] #26 
* [x] #41
* [ ] `/\R/` - A linebreak: \n, \v, \f, \r \u0085 (NEXT LINE), \u2028 (LINE SEPARATOR), \u2029 (PARAGRAPH SEPARATOR) or \r\n.

We should also support POSIX bracket expressions, as in:

* [x] #57
* [x] #58
* [x] `/[[:blank:]]/` - Space or tab
* [x] `/[[:cntrl:]]/` - Control character
* [x] `/[[:digit:]]/` - Digit
* [x] `/[[:graph:]]/` - Non-blank character (excludes spaces, control characters, and similar)
* [x] #56
* [x] `/[[:print:]]/` - Like [:graph:], but includes the space character
* [x] `/[[:punct:]]/` - Punctuation character
* [x] `/[[:space:]]/` - Whitespace character (`[:blank:]`, newline, carriage return, etc.)
* [x] #55
* [x] `/[[:xdigit:]]/` - Digit allowed in a hexadecimal number (i.e., `0-9a-fA-F`)

As well as the non-POSIX Ruby-specific character classes:

* [ ] `/[[:word:]]/` - A character in one of the following Unicode general categories Letter, Mark, Number, Connector_Punctuation
* [x] `/[[:ascii:]]/` - A character in the ASCII character set
