### ISSUE TITLE
Support character properties (meta-issue)

### ISSUE THREAD

**Issue by kddnewton** [kddnewton/regular_expression#8]
The Ruby regex engine includes character property matchers, which are very similar to character classes. They are described here: https://ruby-doc.org/core-3.0.0/Regexp.html#class-Regexp-label-Character+Properties. We should support this syntax as well.

The `\p{}` construct matches characters with the named property, much like POSIX bracket classes.

- [x] #76
- [x] #77
- [x] `/\p{Blank}/` - Space or tab
- [x] `/\p{Cntrl}/` - Control character
- [x] `/\p{Digit}/` - Digit
- [x] `/\p{Graph}/` - Non-blank character (excludes spaces, control characters, and similar)
- [x] #79
- [x] `/\p{Print}/` - Like \p{Graph}, but includes the space character
- [x] `/\p{Punct}/` - Punctuation character
- [x] `/\p{Space}/` - Whitespace character ([:blank:], newline, carriage return, etc.)
- [x] #78
- [x] `/\p{XDigit}/` - Digit allowed in a hexadecimal number (i.e., 0-9a-fA-F)
- [ ] `/\p{Word}/` - A member of one of the following Unicode general category Letter, Mark, Number, Connector_Punctuation
- [x] `/\p{ASCII}/` - A character in the ASCII character set
- [ ] `/\p{Any}/` - Any Unicode character (including unassigned characters)
- [ ] `/\p{Assigned}/` - An assigned character

A Unicode character's _General Category_ value can also be matched with `\p{Ab}` where `Ab` is the category's abbreviation as described below:

- [ ] `/\p{L}/` - 'Letter'
- [ ] `/\p{Ll}/` - 'Letter: Lowercase'
- [ ] `/\p{Lm}/` - 'Letter: Mark'
- [ ] `/\p{Lo}/` - 'Letter: Other'
- [ ] `/\p{Lt}/` - 'Letter: Titlecase'
- [ ] `/\p{Lu}/` - 'Letter: Uppercase
- [ ] `/\p{Lo}/` - 'Letter: Other'
- [ ] `/\p{M}/` - 'Mark'
- [ ] `/\p{Mn}/` - 'Mark: Nonspacing'
- [ ] `/\p{Mc}/` - 'Mark: Spacing Combining'
- [ ] `/\p{Me}/` - 'Mark: Enclosing'
- [ ] `/\p{N}/` - 'Number'
- [ ] `/\p{Nd}/` - 'Number: Decimal Digit'
- [ ] `/\p{Nl}/` - 'Number: Letter'
- [ ] `/\p{No}/` - 'Number: Other'
- [ ] `/\p{P}/` - 'Punctuation'
- [ ] `/\p{Pc}/` - 'Punctuation: Connector'
- [ ] `/\p{Pd}/` - 'Punctuation: Dash'
- [ ] `/\p{Ps}/` - 'Punctuation: Open'
- [ ] `/\p{Pe}/` - 'Punctuation: Close'
- [ ] `/\p{Pi}/` - 'Punctuation: Initial Quote'
- [ ] `/\p{Pf}/` - 'Punctuation: Final Quote'
- [ ] `/\p{Po}/` - 'Punctuation: Other'
- [ ] `/\p{S}/` - 'Symbol'
- [ ] `/\p{Sm}/` - 'Symbol: Math'
- [ ] `/\p{Sc}/` - 'Symbol: Currency'
- [ ] `/\p{Sc}/` - 'Symbol: Currency'
- [ ] `/\p{Sk}/` - 'Symbol: Modifier'
- [ ] `/\p{So}/` - 'Symbol: Other'
- [ ] `/\p{Z}/` - 'Separator'
- [ ] `/\p{Zs}/` - 'Separator: Space'
- [ ] `/\p{Zl}/` - 'Separator: Line'
- [ ] `/\p{Zp}/` - 'Separator: Paragraph'
- [ ] `/\p{C}/` - 'Other'
- [ ] `/\p{Cc}/` - 'Other: Control'
- [ ] `/\p{Cf}/` - 'Other: Format'
- [ ] `/\p{Cn}/` - 'Other: Not Assigned'
- [ ] `/\p{Co}/` - 'Other: Private Use'
- [ ] `/\p{Cs}/` - 'Other: Surrogate'

Lastly, `\p{}` matches a character's Unicode script. The following scripts are supported:

> Arabic, Armenian, Balinese, Bengali, Bopomofo, Braille, Buginese, Buhid, Canadian_Aboriginal, Carian, Cham, Cherokee, Common, Coptic, Cuneiform, Cypriot, Cyrillic, Deseret, Devanagari, Ethiopic, Georgian, Glagolitic, Gothic, Greek, Gujarati, Gurmukhi, Han, Hangul, Hanunoo, Hebrew, Hiragana, Inherited, Kannada, Katakana, Kayah_Li, Kharoshthi, Khmer, Lao, Latin, Lepcha, Limbu, Linear_B, Lycian, Lydian, Malayalam, Mongolian, Myanmar, New_Tai_Lue, Nko, Ogham, Ol_Chiki, Old_Italic, Old_Persian, Oriya, Osmanya, Phags_Pa, Phoenician, Rejang, Runic, Saurashtra, Shavian, Sinhala, Sundanese, Syloti_Nagri, Syriac, Tagalog, Tagbanwa, Tai_Le, Tamil, Telugu, Thaana, Thai, Tibetan, Tifinagh, Ugaritic, Vai, and Yi.
