### ISSUE TITLE
Support more anchors (meta-issue)

### ISSUE THREAD

**Issue by kddnewton** [kddnewton/regular_expression#9]
We already support some anchors for regex, but we should support all of them. They are listed below:

- [x] `^` - Matches beginning of line
- [x] `$` - Matches end of line
- [x] `\A` - Matches beginning of string.
- [ ] `\Z` - Matches end of string. If string ends with a newline, it matches just before newline
- [x] `\z` - Matches end of string
- [ ] `\G` - Matches first matching position
- [ ] `\b` - Matches word boundaries when outside brackets; backspace (0x08) when inside brackets
- [ ] `\B` - Matches non-word boundaries
